import {displayToImagePoint,makeControlPoint} from './calibration.mjs';
const expected={width:6600,height:10200,kmPerPx:.275};
const names=['Calimport','Athkatla',"Baldur's Gate",'Waterdeep','Neverwinter','Luskan'];
const points=[];let img=null;
const stage=document.querySelector('#stage'),targets=document.querySelector('#targets'),out=document.querySelector('#output'),info=document.querySelector('#imageInfo');
function renderTargets(){targets.innerHTML='';names.forEach((n,i)=>{const li=document.createElement('li');li.textContent=n+(points[i]?` — (${points[i].x_px}, ${points[i].y_px})`:'');li.className=points[i]?'done':i===points.length?'current':'';targets.appendChild(li);});}
function renderMarkers(){stage.querySelectorAll('.marker').forEach(x=>x.remove());if(!img)return;for(const p of points){const m=document.createElement('div');m.className='marker';m.style.left=(p.u*100)+'%';m.style.top=(p.v*100)+'%';m.innerHTML=`<span>${p.name}</span>`;stage.appendChild(m);}}
function renderOutput(){out.value=JSON.stringify({schema_version:1,map:'sword_coast_campaign_map_v1',image:{natural_width_px:img?.naturalWidth??null,natural_height_px:img?.naturalHeight??null},control_points:points},null,2);renderTargets();renderMarkers();}
document.querySelector('#file').onchange=e=>{const f=e.target.files[0];if(!f)return;const url=URL.createObjectURL(f);img=new Image();img.onload=()=>{stage.innerHTML='';stage.appendChild(img);info.textContent=`Loaded ${img.naturalWidth} × ${img.naturalHeight}px${img.naturalWidth===expected.width&&img.naturalHeight===expected.height?' · matches vault config':' · differs from vault config'}`;points.length=0;renderOutput();};img.src=url;};
stage.onclick=e=>{if(!img||points.length>=names.length||e.target.classList.contains('marker'))return;const r=img.getBoundingClientRect();const p=displayToImagePoint({clientX:e.clientX,clientY:e.clientY,left:r.left,top:r.top,displayWidth:r.width,displayHeight:r.height,naturalWidth:img.naturalWidth,naturalHeight:img.naturalHeight});points.push(makeControlPoint(names[points.length],p,img.naturalWidth,img.naturalHeight));renderOutput();};
document.querySelector('#undo').onclick=()=>{points.pop();renderOutput();};document.querySelector('#reset').onclick=()=>{points.length=0;renderOutput();};document.querySelector('#copy').onclick=async()=>{await navigator.clipboard.writeText(out.value);};renderOutput();
